stages:
    - test
    
test:
    stage: test
    image: python:3.8
    script:
        - python3.8 -m pip install pipenv
        - pipenv install
        - pipenv install coverage
        - pipenv run coverage run --source='.' manage.py test
        - pipenv run coverage report -m
        - pipenv run coverage html
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        paths:
            - htmlcov
        