version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install coverage
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
            pipenv run coverage run --source='.' manage.py test
            pipenv run coverage report -m
            pipenv run coverage html
      - store_test_results:
        path: htmlcov
      - store_artifacts:
        path: htmlcov

workflows:
  main:
    jobs:
      - test
