version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install coverage
      - run:
          command: |
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
      - run:
          command: |
            ls -a
            pipenv run coverage run --source='.' manage.py test
      - run:
          command: |
            pipenv run coverage report -m
            pipenv run coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov