version: '3'

services:

  web:
    build:
      context: ../../
      dockerfile: dockerfiles/backend/Dockerfile
    env_file:
      - .env
    command: pipenv run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/api/static
      - media:/api/media
    
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postrgesql/data/
    environment:
      - POSTGRES_USER=django_test
      - POSTGRES_PASSWORD=django_test
      - POSTGRES_DB=django_test

volumes:
  postgres_data:
  static:
  media: