version: "3.2"

services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "xxx:xxx"

  # postgres:
  #   restart: always
  #   image: postgres:<ver>
  #   environment:
  #     POSTGRES_USER: $DB_USER
  #     POSTGRES_PASSWORD: $DB_PASS
  #     POSTGRES_DB: $DB_NAME
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   ports:
  #     - "xxxx:xxxx"

  # backend:
  #   ports:
  #     - "xxxx:xxxx"
  #   volumes:
  #     - ./backend:/backend
  #   command: /scripts/wait-for-it.sh ${DB_HOST}:${DB_PORT} -- python /backend/manage.py runserver 0.0.0.0:xxxx

  frontend:
    # volumes:
    #   - ./frontend/src:/frontend/src
    #   - ./frontend/public:/frontend/public
    command: yarn start
    ports:
      - "3000:3000"
